### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by wibed** [itay-grudev/cloudnative-pg-charts#7]
https://cloudnative-pg.io/documentation/current/api_reference/#PostgresConfiguration

**Comment by itay-grudev** [comment]
Should be replaced with: https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-PostgresConfiguration

I'll make sure it's updated.

**Comment by itay-grudev** [comment]
Resolved in the latest release.
